resources:
  '*':
    requests:
      cpu: 1000m
      memory: 1Gi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.4"
  namespace: ocp
tests:
- as: my-test
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: /peak/installandtest.sh
      from: odh-manifests-tests
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
    workflow: ipi
zz_generated_metadata:
  branch: master
  org: opendatahub-io
  repo: odh-manifests
