build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: tests/Dockerfile
  from: ""
  to: odh-manifests-tests
resources:
  '*':
    requests:
      cpu: 1000m
      memory: 1Gi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.4"
  namespace: ocp
tests:
- as: my-test
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: /peak/installandtest.sh
      from: odh-manifests-tests
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: opendatahub-io
  repo: odh-manifests
